### ISSUE TITLE
Time to repair

### ISSUE THREAD

**Issue by raisafp** [MozillaFestival/open-leaders-7#100]
Project Lead: Raisa Ferrer Pizarro

Mentor: Luis Fraguada

Welcome to OL7, Cohort A! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 29): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 5): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 12): Mentorship call
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 19): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [ ] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [ ] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [ ] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [ ] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [ ] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by raisafp** [comment]
**Project vision**

25/Feb (Update)

> The Time to Repair project works with tailors and seamstresses in Lima, Peru to develop a collaborative online platform where they can announce their services to consumers looking to repair their garments. The project connects diverse generations to achieve more sustainable garment consumption practices.

Older one:
Time to repair is about working with tailors and seamstresses in Lima to develop a collaborative database so that they can benefit from internet exposure and people can find allies in them to repair garments of their own / Connecting diverse generations to achieve more sustainable practices.

**Open canvas**
Available here: https://docs.google.com/presentation/d/1r2a0UgUgqlBww61Y-lXJOBkH_V4H5cS85QaQwZSc_QQ/edit?usp=sharing

**Roadmap**
Available here: https://docs.google.com/document/d/1vlkMbcdTLdwKIplNW3o5HpcqVIzKeXczrzXRA1_VWRE/edit

Would love some feedback 👍

**Comment by foretia** [comment]
Great, you are having an interesting topic here especially that aspect of taking advantage of the broadband technology to expose elderly seamstresses

**Comment by msoka86** [comment]
Interesting project! But is your target group digitally savvy enough to use the platform?

**Comment by victordiaz** [comment]
I like the idea! As @msoka86 mentioned, maybe people in their 50s or 60s don't know very well how to use complex digital tools. So UX is very important here! Do you know if those people use already some other type of digital communication tools? Maybe Whatsapp or Facebook? I know is now very ideal in this context but perhaps researching how they use those communities maybe it can inspire you?

**Comment by raisafp** [comment]
> Interesting project! But is your target group digitally savvy enough to use the platform?

I Think they are not. I

**Comment by raisafp** [comment]
> I like the idea! As @msoka86 mentioned, maybe people in their 50s or 60s don't know very well how to use complex digital tools. So UX is very important here! Do you know if those people use already some other type of digital communication tools? Maybe Whatsapp or Facebook? I know is now very ideal in this context but perhaps researching how they use those communities maybe it can inspire you?

Yes... those are very interesting questions. I recently wrote my roadmap (first draft: https://docs.google.com/document/d/1vlkMbcdTLdwKIplNW3o5HpcqVIzKeXczrzXRA1_VWRE/edit)... I think I will invest some time on understanding who these professionals are and how do they interact on the internet! It will be difficult to create a useful platform if I don't have them in mind :(

**Comment by raisafp** [comment]
> Interesting project! But is your target group digitally savvy enough to use the platform?

I have to find out! And develop something that it's very intuitive for them...
