### ISSUE TITLE
Program Civica 

### ISSUE THREAD

**Issue by Sarah0Sharif** [MozillaFestival/open-leaders-7#105]
Project Lead: Sarah Sharif (Sarah0Sharif) 
Mentor: Meag Doherty
Mentor profile: https://www.mozillapulse.org/profile/479

Welcome to OL7, Cohort E! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 31): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 7): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-culture-track-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 14): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 21): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Culture Track Syllabus](https://mzl.la/ol7-culture-track-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by Sarah0Sharif** [comment]
**Design
Build
Empower**

Design for Understanding: 8/10
Design for Sharing: 7/8 
Design for Participation & Inclusion: 4/6
16/24

Build for Understanding: 9/10
Build for Sharing: 8/10 
Build for Participation & Inclusion: 9/10
26/30

Empower for Understanding: 6/6
Empower for Sharing: 6/6
Empower for Participation & Inclusion: 5/6
17/18

Total: 59/72
Reflection: I'm surprised by some of the results and then not surprised by others...the empower piece I know I feel strong given my community organizing background...the design aspects still are places of weakness, insecurity, and limited knowledge. Very curious to explore this. Overall, I feel content in current approaches to openness which I hold...but excited to work hard on these areas of improvement over the coming months.

**Comment by Sarah0Sharif** [comment]
### **WELCOME TO PROGRAM CIVICA**

<p align="center">
“Knowledge is a thousand times more valuable than silver or gold.”  ― Matshona Dhliwayo
</p>

### WHAT IS PROGRAM CIVICA?
Program Civica is an open education platform where we can have instructional content on emerging topics such as design thinking, civic hacking, open leadership, and more. It's a free platform and will be hosted by [Experimental Civics.](https://www.experimentalcivics.io/) 

<p align="center">
<img src="https://user-images.githubusercontent.com/46907639/53046364-77e6f500-3455-11e9-9ebf-1f46983397e1.png" width="150" height="150">
</p>

[Program Civica on Podbean](https://experimentalcivics.podbean.com/)

### WHO IS [EXPERIMENTAL CIVICS](https://www.experimentalcivics.io/) ?
Experimental Civics is an innovation consultancy where we help our clients experiment with their ideas to expedite innovation. 

<p float="left">
  <img src="https://user-images.githubusercontent.com/46907639/53046526-dd3ae600-3455-11e9-8d90-c3050b40ef3f.png" width="300" height="300" />
  <img src="https://user-images.githubusercontent.com/46907639/53047665-8aaef900-3458-11e9-8e53-b59c324b5a36.png" width="250" height="300"/> 
</p>

### PROJECT STATEMENT 

> Working intimately with leaders to educate them on open leadership through the lens of innovation so they can revamp their existing methodology to achieve greater openness in their organization. The impact will improve team performance, productivity, and happiness. 

### ROADMAP

I wanted to develop a robust, but short-and-sweet roadmap for generating a season on openness based on the research questions we outlined in our original application. The target audience is outside of the vast technology, open-source sphere and these lucky folks are usually based in the nonprofit / gov / corporate sectors. Of course, our content can be useful to all 

### MILESTONE 1: Research current barriers on openness

- [x] Step 1: Establish research questions

- What are the best case studies out there? 
- What tools are typically used to assess openness? 
- Where are the tools lacking? 
- Where are the hidden challenges? 
- What should people know about openness?
- What are effective ways to implement openness?
- Why is openness hard?
- What are the short-term and long-term benefits of openness?

- [x] Step 2: Research numerous activities and programs which offer open leadership trainings in addition to Mozilla

- [x] Step 3: Interview experts on openness from various backgrounds and consult on the research questions

### MILESTONE 2: Draft 7 scripts based on the top research question answers and bake in actionable activities in each recap

- [x] Step 1: Complete first round of drafts for 1-7 scripts (mentor feedback) 

- [x] Step 2: Complete second round of drafts for 1-7 scripts (cohort feedback) 

- [x] Step 3: Complete third round of drafts for 1-7 scripts (program feedback) 

- [x] Step 4: Prep all final scripts for production 

### MILESTONE 3: Submit final scripts for voiceover production and format work

- [ ] Step 1: Complete script submission with set direction for voiceover artist 

- [ ] Step 2: Ensure all Podbean and channel platforms are ready for distribution 

- [ ] Step 3: Convert all audio files to .mp3 

### MILESTONE 4: Publish all audio files and promote the channel

- [ ] Step 1: Ensure all functionality and content is sound prior to promotion 

- [ ] Step 2: Track promotion and success metrics over an interval of time 

- [ ] Step 3: Promote across numerous channels 

- [ ] Step 4: Begin to track external feedback and source new ideas for future open-focused pieces

### MILESTONE 5: Review case study with cohort and finalize program 

- [x] Step 1: Prep metrics and case study material for end-of Open Leaders Program submission

- [x] Step 2: Share case study with cohort for future collaborations and ideas

**Comment by Sarah0Sharif** [comment]
[ProgramCivica_OpenCanvas.pdf](https://github.com/MozillaFestival/open-leaders-7/files/2886637/ProgramCivica_OpenCanvas.pdf)

**Comment by patmatsu** [comment]
This project looks really good.

**Comment by Sarah0Sharif** [comment]
<p align="center">
<img src="https://user-images.githubusercontent.com/46907639/53525297-69c95200-3aaf-11e9-910d-cc5b7543825b.png" width="500" height="500">
</p>

**Comment by Sarah0Sharif** [comment]
> This project looks really good.

**Comment by pomodoro24** [comment]
> [ProgramCivica_OpenCanvas.pdf](https://github.com/MozillaFestival/open-leaders-7/files/2886637/ProgramCivica_OpenCanvas.pdf)

Great Open Canvas! Very clear and concise

**Comment by nirmalakrish** [comment]
The program civica - the open education platform idea is great.
the creative thinking  to write canvas and roadmap is very impressive.

**Comment by kswhitney** [comment]
Roadmap comment - I really enjoy the program idea. Can you consider using a different word than "blind" for "blind spots"?  This is a disability metaphor and disability activists have written extensively encouraging people not to use disability as metaphor. See for example - http://meloukhia.net/2015/05/disability_as_metaphor_and_why_you_shouldnt/

**Comment by Sarah0Sharif** [comment]
@kswhitney - TY. Of course, I had used it as reference to a driving term, but I can see the other side as well. What do you recommend? --- How about hidden challenges? current deficits?

**Comment by Sarah0Sharif** [comment]
@nirmalakrish + @belengimenezcic: TY for your recognition, all we can do is try our very best!

**Comment by Sarah0Sharif** [comment]
[Case study_ Program Civica.pdf](https://github.com/MozillaFestival/open-leaders-7/files/3134806/Case.study_.Program.Civica.pdf)

**My OL7 culture track story**
I was exposed to the Open Leaders Program through several Mozillans and contacts I worked closely with around the Community Gigabit Fund. I got to experience MozFest and I fell in love with the open community. I wanted to improve and be an even better open leader myself so I applied and here I am. 

I chose this project because this is a HUGE part of the initial work which needs to happen with all open leaders and I want to support them as they start their tremendous efforts to implement openness with themselves, their teams, their organizations, and throughout their careers. 

We have a ton of work to do and we want to entice people in their busy lives to be curious about what openness can provide for them. 

**Key accomplishments**

**Empowerment** 

**Culture Cohort E (Envited)** I can’t find a way to describe how meaningful the entire experience was in terms of understanding how empowerment played a large role within the Culture Cohort E (Envited). From our discussions, to learning about other work happening, to the materials, and how to engage with others in the community. I’m certainly happy to be walking away from this experience understanding the benefits of the open online community and to support other leaders collectively. 
Mentor I really enjoyed the discussions I shared with my mentor and I was lucky to run into her in both New York City (NYC) and in Austin. We had the most meaningful conversations when in-person. I remember having a low moment in NYC and my mentor was incredible empathetic, inspiring, and understanding of the work and who I was. 

**Real Stories.** I feel that within the Cohort conversations we were able to talk about how the material applied or didn’t apply to our work. I really enjoyed the stories I heard, shared, and listened to within the Cohort. I also learned a ton of information in my interview calls with openness experts. I was able to really take the time to dive into the questions I wanted answered.

**Meaningful Content** I know that producing meaningful content was important to me and I feel proud of what I have drafted and created thus far. I hope that it is useful and again...it is meant to just be a launching pad. Some of us have to be at the beginning of engagement while others can take people even further, but sparking curiosity can be the hardest piece with a community. 

**Key understandings**

**Design for Curiosity** 
I certainly understand the importance of curiosity when engaging with any and all audiences on openness. I think that the terms are still so vague and aren’t really resonating with people....especially when you couple “open” with “leadership.” I feel that I have learned how to improve my understanding, my messaging, and how to weave in play and intrigue.  

**Design for People**

I know that I have experienced how to design for community projects, but I really learnt how to design for organizations. I realized that open leaders and organizations also need dedicated support since the largest barriers are usually existing structures. 

**Barriers**

I have been able to take a deeper dive into the barriers which prove to hinder open workflows, open culture, open leadership, and openness in general. I realized so much about the barriers and how we are still struggling with understanding people. At the end of the day, I realized that when it comes to introducing open culture, we need to start with people, and take it very slow. Although, we need to make steady progress as leaders. 

**Role of Compassion** 

In developing content and after listening to the interviews of the Open Experts, it was very apparent that compassion was the central theme across introducing openness to dealing with closed systems. Compassion became the key ingredient to developing messaging, designing for those who were unfamiliar, and those who were resistance. 

**Next steps**

Launch the New Season of Program Civica: Open Leadership
Promote to larger community and network 
Continue to be engaged with the Mozilla Network
Continue to be engaged with the MozFest Network 
Writing a blog about my experience 
Staying connected
I want to continue to support people through GitHub
I would love to continue working with Culture Cohort E participants 
Promote to larger community and network 
Continue to engage with the Open Leaders Program (Mentorship, Volunteerism, etc.) 
Promote the next cohort call 

**Acknowledgements**

<<Share the love and give shoutouts to people who helped you along the way.>>
<3 

Meag Doherty
Maya Wagoner
Chad Sansing 
Amanda Innes

**Comment by Sarah0Sharif** [comment]
To anyone and everyone following this project, we've hit a few delays with the voiceover, but the new season on open leadership will be launching this Summer at the latest. **Thank you!**
