### ISSUE TITLE
userli

### ISSUE THREAD

**Issue by t2d** [MozillaFestival/open-leaders-7#109]
Project Lead: t2d

Mentor: triaslucia

Welcome to OL7, Cohort A! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 29): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 5): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 12): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 19): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [x] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [x] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by t2d** [comment]
Vision statement: I'm working with privacy enthusiasts to create a web front-end for encrypted mailboxes. With this system, hackers and server administrators  wouldn't have the possibility to read users mails.

**Comment by triaslucia** [comment]
Hi great that you started!
It wuold be nice if you could describe a bit more what  ' privacy enthusiasts ' are in this context. From what I understood so far, there is a specific type of 'enthutiasts' that your project need to involves, e.g. concerning tech knowing, isn't it?
That'll help both, your team and people not to feel frustrated by not matching each other :)

**Comment by t2d** [comment]
![open canvas userli](https://user-images.githubusercontent.com/1834580/52859342-bcf4e980-312c-11e9-8b1d-ff77ce494b8b.png)

**Comment by annefou** [comment]
That's not my topic so my comments/questions are most likely stupid... Your project seems to me very interesting; does your project aim at increasing the number of "Privacy enthusiasts"? I mean do you plan to also explain why it is so important and why it matters; trying to convince those who do not know.

**Comment by t2d** [comment]
[README with License](https://github.com/systemli/user-management/blob/master/README.md)

**Comment by foretia** [comment]
> Vision statement: I'm working with privacy enthusiasts to create a web front-end for dovecot with encrypted storage so end-user don't have to worry about server administrators reading their mail.

I find it very difficult to understand your vision statement, please can you breakdown some of terms for layman understanding

**Comment by Botsyoelily** [comment]
The vision is a good one. What of if the server administrators reading the mail could avoid hacking attempts since they will be detected by the administrators

**Comment by triaslucia** [comment]
Great that you did the O.Canvas. Looks way more organized and clear! 

I was wondering, Could you explain a bit more on the Unique Value. Why wuold I like to run my own copy of the system? maybe it would be  usefull to explain the benefits of Userli , I think there is were actually your UVP is, and its important that "your user" get's it as clear as possible.

**Comment by t2d** [comment]
Code of Conduct: https://systemli.github.io/userli/development/code_of_conduct/

**Comment by t2d** [comment]
Persona 1:

Adriana is a systems administrator. She works for an NGO and is tasked to administer a mail server. The NGO has decided, they don't want to be able to surveil their employees and co-workers. Therefore, they look into mailbox encryption. Adriana has some experience with Debian Linux and scripting languages. 

Persona 2:
Bertha is using a Userli instance. She picked a mail provider that encrypts her mailbox because she values her privacy. She's involved in an environmental campaign and is worried someone might try to access her mail. She tried to use GPG, but has failed. Her fellows didn't share the enthusiasm. So she had no-one to write to. She has no experience with and interest in coding.

**Comment by t2d** [comment]
> does your project aim at increasing the number of "Privacy enthusiasts"? I mean do you plan to also explain why it is so important and why it matters; trying to convince those who do not know.

@annefou Thank you for your feedback. The only plan we currently have, is to motivate users that are already on the platform (for whatever reason) to enhance their security and security. The idea was to provide little steps and nudge users to go them. For example: "Create your first alias address to protect from inter-platform tracking"

**Comment by t2d** [comment]
> What of if the server administrators reading the mail could avoid hacking attempts since they will be detected by the administrators

@Botsyoelily Thank you for checking out this topic. I have trouble understanding your question. Do you think it could be bad to encrypt mail, because the administrator can't check for bad content?

**Comment by t2d** [comment]
> I find it very difficult to understand your vision statement, please can you breakdown some of terms for layman understanding

@foretia Thank you for your feedback. I tried to use a little bit easier wording and shorter sentences. Do you thinks it's better now?

**Comment by t2d** [comment]
# Project Mission & Summary

Userli is a web-frontend that allows to (self-) manage mail users and encrypt their mailboxes.

## [Milestone Easier Installation (2.1.0)](https://github.com/systemli/userli/milestone/10)
* Create Ansible Role
* Update install instructions
* public/bundles missing from release

## [Milestone User Testing](https://github.com/systemli/userli/milestone/13)

* Conduct three in-person user testing sessions
* Create five simple tasks and let five people try them and messure how much time they took
* What would people like to do with the system or expect it to be capable?

## [Milestone More security options](https://github.com/systemli/userli/milestone/12)
* Allow to switch to TLS-only connection
* Incorporate feedback from Milestone User Testing 

(atm, we're doing this only with GitHub Milestones, so I'm posting this draft roadmap here directly)
