### ISSUE TITLE
Tour Delirio. Salsa and Surveillance

### ISSUE THREAD

**Issue by julianitaquetal** [MozillaFestival/open-leaders-7#24]
Project Lead: https://github.com/julianitaquetal

Mentor: https://github.com/dannyrayman

Welcome to OL7, Cohort B! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 29): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 5): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 12): Mentorship call
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [ ] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 19): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [ ] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [ ] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [ ] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [ ] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by julianitaquetal** [comment]
### Vision statement:
 I’m working with collaborators to improve Tour Delirio´s impact so the audience can make awareness about the surveillance that is present in our daily lives through governments, corporations, and social relationships.

(ノ^_^)ノ

**Comment by julianitaquetal** [comment]
### Open Canvas for Tour Delirio.  ヽ(⌐■_■)ノ♪♬

**[English version](https://docs.google.com/presentation/d/1juk3VMEUKMHLqOlCjylYMoxYwSRBO0ecmw0T8PIVSaM/edit#slide=id.p)** 
**[Spanish version](https://docs.google.com/presentation/d/1fsNMVgo3FMeFu2tnv2yad25UB8GBYnktDdC0ZSxdimk/edit#slide=id.p)**

**Comment by julianitaquetal** [comment]
### Roadmap draft for Tour Delirio
[English and Spanish here](https://docs.google.com/document/d/1AxRBaeTeUOmsw-3gjm6kkRDVyr1bC5FShQaU5Jip6bc/edit)

♪(┌・。・)┌

**Comment by julianitaquetal** [comment]
Final roadmap here: https://github.com/tourdelirio/Tour-delirio-salsa-y-vigilancia/issues/1

**Comment by julianitaquetal** [comment]
### **POP MY EVENT**

**PURPOSE:**

- To bring together a community of collaborators to improve Tour Delirio´s impact in order to make awareness about the surveillance that is present in our daily lives. 

**OUTCOMES:**

- New stories created with the open graphics resources of Tour Delirio availables in https://archive.org/details/@tour_delirio_ 

- Have translations of the existing content of Tour Delirio into other languages

- A growing community of collaborators of the project.

**PROCESS**

- Create a repository with all Tour Delirio resources

- Launch a social media campaign to invite people to create new stories using TD resources as templates for their own stories of surveillance and privacy.

- Invite others to share their stories in social media using the tag @tourdelirio or the hashtag #tourdelirio

- Facilitate a collaborative translation process in order to collaborators can help us with the translation of the existing content of Tour Delirio into other languages

**Comment by julianitaquetal** [comment]
Hi all! If you want to know about our progress and how you can be part of Tour Delirio, visit our [GitHub repository](https://github.com/tourdelirio/Tour-delirio-salsa-y-vigilancia/issues)

♪┏(°.°)┛

**Comment by tourdelirio** [comment]
**Final demos!**
This is Tour Delirio presentation [written](https://docs.google.com/document/d/1xIt6H69tYCTtSxZUDqfwQOzOQb5GAWXvKEMvwRJH3G0/edit#) and [visual](https://drive.google.com/file/d/1COrCCNVpAyq3C0recZFRJvODlzZPzMC7/view) 

Watch our Cohort aka "MozMavericks" on Tues, Apr 30th — 16:00 UTC. Stream: https://www.youtube.com/watch?v=Amaw17K-u0Y. Notes: https://mzl.la/ol7-demos-b
