### ISSUE TITLE
Xenoform Labs

### ISSUE THREAD

**Issue by scottkildall** [MozillaFestival/open-leaders-7#31]
Project Lead: scottkildall

Mentor: diwanshi

Welcome to OL7, Cohort C! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 30): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 6): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 13): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 20): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [x] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [ ] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [ ] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [x] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by scottkildall** [comment]
Mission Statement:

Xenoform Labs provides an artist-in-residency program for visiting new media artists to develop experimental work and show their prototypes and ideas to artists, thinkers, curators and writers in the San Francisco area.

**Comment by pablodiegoss** [comment]
Hey, we from #36 Jandig, read your mission statement but didn't quite got the "artist-in-residency program", so, you guys have a space for artists to visit and share work? Maybe the ["What you are doing part"](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/#assignment--write-your-vision-or-mission-statement) could be improved :)

**Comment by scottkildall** [comment]
> Hey, we from #36 Jandig, read your mission statement but didn't quite got the "artist-in-residency program", so, you guys have a space for artists to visit and share work? Maybe the ["What you are doing part"](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/#assignment--write-your-vision-or-mission-statement) could be improved :)

Thanks. I now realize that "artist-in-residency" is something that people in the art world know all about, but is not apparent to others. I'll see if I can clear up this definition.

**Comment by scottkildall** [comment]
[Canvas Document](https://docs.google.com/presentation/d/1o4Dpru5YvAOTcNw9xoq_SIpuqpCGFFmNOSIe8AdiMp8/edit?usp=sharing) with the question:

**How do you make an art residency be “open”?**

Admittedly, I'm stuck on the solution, which is one of the reasons I'm in the mentorship program.

**Comment by scottkildall** [comment]
[ReadMe file is here ](https://github.com/scottkildall/xenoformlabs)(along with a GitHub repo for Xenoform Labs)

**Comment by scottkildall** [comment]
[GitHub Repo]((https://github.com/scottkildall/xenoformlabs)) is now up with License and an updated ReadMe file which has the embedded RoadMap in it, which is also here:

The Art Thinking diagram is a methodology that I've developed by which artists produce work, akin to the scientific method or design thinking. This is one of the core ideas I'm wanting to get written up and finished. So yea, it seems a little vague right now.

**Roadmap**

**Goals**
(1) Have an online repository that is useful that people can look at to understand the Inquiry-Experimentation-Shape work that artists are doing at Xenoform Labs

(2) Publish my “Art Thinking” diagram

(3) Well-designed website for Xenoform Labs that archive this work.

**Milestone: Online Repository [2/28/19]**
Setup GitHub for Xenoform Labs (done: https://github.com/scottkildall/xenoformlabs)

Put content from previous residencies (Bruno + Ruth and Nathaniel Stern) on there

Cross-reference on XL Website

**Milestone: Xenoform Labs Website [3/31/19]**

Find web designer [done]

Investigate Recurse as a model: https://www.recurse.com/

Begin oversight and XL website work (waiting on her)

Develop content for past residents and future residents

Approve final content

**Milestone: Publish Art Thinking diagram [4/30/19]**
Confirm publishing venue with Rhiannon

Seek out other venues for publishing

Think about other connectors for where to publish it

Actually write the article itself

**Comment by theo-bech** [comment]
I read most of the stuff on your issue and repo and I find your project very interesting! I've also given the main question (how do you make an art residency open) some thought, so here's some stuff that came to mind:

In my understanding, an art residency is a residency in the literal sense, right? So I think you need to get this question out of the way first: which are you making open, the residency (process of creating art in a new space) or the art? Are you building an open collaborative/contributive network where artists-in-residency document and discuss their experiences as residents, or are you facilitating the exchange of (art) ideas within and across residency spaces? 

If it's the latter, then finding ways to make your art diagram process open might be what you're looking for. Maybe idea-mapping software is a good place to start? It's usually cooperative/cloud-based so it fits the bill. (I've never used it though so don't take my word for it 😅)

Or maybe you could create a communication channel where residents help each other through the technical hassle of their projects? (there's a lot of troubleshooting involved in new media art, right?)

Sorry if that's a little vague, I don't have experience in anything like your work! I hope that helps, and good luck with your project!

**Comment by scottkildall** [comment]
Thanks @theo-bech! Yes, that is a good thing to clarify and I had conflated the two. The art process is what I'm looking to make open *and* the source code (when applicable). The final artwork, well, that is up to the artists themselves.

So, I guess figuring out what this means for making the process open would be helpful. I think it's more about the ideas and brainstorming than the technological hassle — each resident has different techs their working with.

Stuff for me to think about this weekend. Thanks!

**Comment by scottkildall** [comment]
after much struggle, I've got a second GitHub account, this one for Xenoform Labs and its 3 residencies thus far.

Here's a better link for the readme file
https://github.com/xenoformlabs/residencyprogram/blob/master/README.md

**Comment by scottkildall** [comment]
Some updates:
- Website structure has been redesigned: https://xenoformlabs.com/
- I've asked previous resident artists to contribute to the blog and will request this of new artists, too.
- Events are now a side project — these are Workshops/Ad Hoc events or anything else that deserves documentation

I'm still struggling with the question of how to: "Have an online repository that is useful that people can look at to understand the Inquiry-Experimentation-Shape work that artists are doing at Xenoform Labs".

**Comment by scottkildall** [comment]
Milestone: Online Repository [2/28/19]

This has been accomplished, a couple weeks ago.
