### ISSUE TITLE
NordicESMhub

### ISSUE THREAD

**Issue by annefou** [MozillaFestival/open-leaders-7#40]
Project Lead:  Anne Fouilloux (github username **annefou**)

Mentor: Bérénice Batut

Welcome to OL7, Cohort A! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 29): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 5): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 12): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 19): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [x] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [x] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [x] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by annefou** [comment]
**Vision/Mission statement:**

I’m working with the Nordic Earth System Modeling Community to build a Nordic ESM hub (Denmark, Finland, Sweden, Iceland, Estonia, Norway) for sharing knowledge, codes (climate models, Galaxy climate data analysis and visualization tools), training tutorials so that our contributions for to the Coupled Model Intercomparison Project can be easily exploited/reused within the Nordic countries and beyond, and by other communities. 

I am working open to:
- prevent students, PhDs, postdocs, researchers from re-inventing the wheel (where to find NorESM climate data, which model configurations are supported to run, how to visualize data over the Nordics i.e. which projection to use, etc.)  
- provide the Nordic ESM community with up to date information (i.e. documentation that can be easily updated by contributors)
- make the Nordic contributions more visible and favor new collaborations.

**Comment by dblana** [comment]
I'm doing a similar thing for motion analysis code (see [here](https://github.com/MozillaFestival/open-leaders-7/issues/54)). Your vision statement is very clear! :+1:

**Comment by annefou** [comment]
My Open Canvas is available at https://docs.google.com/presentation/d/1JJvFRCvNeWsOEo7iabb2--WiyN_urEqElUb9Eua5MNA/edit?usp=sharing

**Comment by annefou** [comment]
# Roadmap

_A hub for sharing knowledge and resources on Earth System Modelling in the Nordic countries_.

The _NordicESMHub_ github organization provides the **Nordic Earth System Modeling Community** with a focal point for sharing knowledge, codes (climate models, Galaxy climate data analysis and visualization tools), training tutorials.

## What do we need to do?

### **Milestone**: Github project

- Create a new Github project at the organization level and link milestones to the roadmap
- Add/update README, LICENSE, CODE_OF_CONDUCT, CONTRIBUTING files in the main repository https://github.com/NordicESMhub/nordicesmhub.github.io and in each existing repository of the NordicESMhub Github organization

### **Milestone**: NordicESMHub Website

Update https://github.com/NordicESMhub/nordicesmhub.github.io to show:
- how the NordicESMhub is organized
- what information can be found depending on who you are (citizen, students, teachers, researchers, etc.)
- what we do
- Calendar of relevant events (workshops/tutorials) in the Nordics
- how to contribute

### **Milestone**: Tools packaging with conda

- NordicESMhub conda channel can be fed automatically through https://github.com/NordicESMhub/esmconda-recipes 

### **Milestone**: Galaxy tools

- Development of Earth System Modeling tools for Galaxy
- Deployment of Earth System Modeling tools in the Galaxy tool shed

### **Milestone**: Galaxy Training for Earth System Modelling

Organize a workshop for learning on
-  how to use Galaxy for Earth System Modelling
- how to develop new tools and deploy them in the Galaxy toolshed

**Comment by Fondestjoel** [comment]
> # Roadmap
> _A hub for sharing knowledge and resources on Earth System Modelling in the Nordic countries_.
> 
> The _NordicESMHub_ github organization provides the **Nordic Earth System Modeling Community** with a focal point for sharing knowledge, codes (climate models, Galaxy climate data analysis and visualization tools), training tutorials.
> 
> ## What do we need to do?
> ### **Milestone**: Github project
> * Create a new Github project at the organization level and link milestones to the roadmap
> * Add/update README, LICENSE, CODE_OF_CONDUCT, CONTRIBUTING files in the main repository https://github.com/NordicESMhub/nordicesmhub.github.io and in each existing repository of the NordicESMhub Github organization
> 
> ### **Milestone**: NordicESMHub Website
> Update https://github.com/NordicESMhub/nordicesmhub.github.io to show:
> 
> * how the NordicESMhub is organized
> * what information can be found depending on who you are (citizen, students, teachers, researchers, etc.)
> * what we do
> * Calendar of relevant events (workshops/tutorials) in the Nordics
> * how to contribute
> 
> ### **Milestone**: Tools packaging with conda
> * NordicESMhub conda channel can be fed automatically through https://github.com/NordicESMhub/esmconda-recipes
> 
> ### **Milestone**: Galaxy tools
> * Development of Earth System Modeling tools for Galaxy
> * Deployment of Earth System Modeling tools in the Galaxy tool shed
> 
> ### **Milestone**: Galaxy Training for Earth System Modelling
> Organize a workshop for learning on
> 
> * how to use Galaxy for Earth System Modelling
> * how to develop new tools and deploy them in the Galaxy toolshed

Impressive Roadmap you have there Anne. Excellent project with clear milestones.

**Comment by Fondestjoel** [comment]
> **Vision/Mission statement:**
> 
> I’m working with the Nordic Earth System Modeling Community to build a Nordic ESM hub (Denmark, Finland, Sweden, Iceland, Estonia, Norway) for sharing knowledge, codes (climate models, Galaxy climate data analysis and visualization tools), training tutorials so that our contributions for to the Coupled Model Intercomparison Project can be easily exploited/reused within the Nordic countries and beyond, and by other communities.
> 
> I am working open to:
> 
> * prevent students, PhDs, postdocs, researchers from re-inventing the wheel (where to find NorESM climate data, which model configurations are supported to run, how to visualize data over the Nordics i.e. which projection to use, etc.)
> * provide the Nordic ESM community with up to date information (i.e. documentation that can be easily updated by contributors)
> * make the Nordic contributions more visible and favor new collaborations.

I like the clarity of your vision and mission statement. Also I commend the ambition of your project.

**Comment by annefou** [comment]
I included a README file with LICENSE and these two files are available at:

- https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/README.md
- https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/LICENSE.md

**Comment by peoplenarthax** [comment]
> **Vision/Mission statement:**
> 
> I’m working with the Nordic Earth System Modeling Community to build a Nordic ESM hub (Denmark, Finland, Sweden, Iceland, Estonia, Norway) for sharing knowledge, codes (climate models, Galaxy climate data analysis and visualization tools), training tutorials so that our contributions for to the Coupled Model Intercomparison Project can be easily exploited/reused within the Nordic countries and beyond, and by other communities.
> 
> I am working open to:
> 
> * prevent students, PhDs, postdocs, researchers from re-inventing the wheel (where to find NorESM climate data, which model configurations are supported to run, how to visualize data over the Nordics i.e. which projection to use, etc.)
> * provide the Nordic ESM community with up to date information (i.e. documentation that can be easily updated by contributors)
> * make the Nordic contributions more visible and favor new collaborations.

You have a very clear vision even though I feel like I am missing what are the benefits of this collaboration and why it is needed.

**Comment by annefou** [comment]
@peoplenarthax So I guess it is definitely not that clear! Thanks for letting me know:

Why this collaboration is important:
- Most climate models are developed in countries (centre of Europe, USA) where the most important areas are definitely not over the Nordic countries. To be valid, climate models need to be "tuned" which means they need to be adapted to the area you are interested in. USA, Europe, China, etc. are not interested by the climate change in the Nordic countries and if their models are not very accurate on these areas, they do not care as it does not have any impact on their population while it is very important for us. 

Why this collaboration is needed:
- The number of inhabitants in each of these Nordic countries is low (between 300 000 inhabitants in Iceland with an average of 6 millions). There are few specialists and it is often difficult to find someone you can talk to or ask questions or even to know that someone has done it before you. For instance, we need to define special grids and visualize climate model outputs with the Nordic countries in the centre of our plots. New students, Phds, postdocs coming from other (mid-latitudes) countries always struggle with it. So the idea is to share the knowledge we have so it becomes less opaque and easier to master for newcomers.

I hope it clarifies a bit. Let me know as I think it is important for me to clarify it so I can clearly express it.
Thanks.

**Comment by peoplenarthax** [comment]
> @peoplenarthax So I guess it is definitely not that clear! Thanks for letting me know:
> 
> Why this collaboration is important:
> 
> * Most climate models are developed in countries (centre of Europe, USA) where the most important areas are definitely not over the Nordic countries. To be valid, climate models need to be "tuned" which means they need to be adapted to the area you are interested in. USA, Europe, China, etc. are not interested by the climate change in the Nordic countries and if their models are not very accurate on these areas, they do not care as it does not have any impact on their population while it is very important for us.
> 
> Why this collaboration is needed:
> 
> * The number of inhabitants in each of these Nordic countries is low (between 300 000 inhabitants in Iceland with an average of 6 millions). There are few specialists and it is often difficult to find someone you can talk to or ask questions or even to know that someone has done it before you. For instance, we need to define special grids and visualize climate model outputs with the Nordic countries in the centre of our plots. New students, Phds, postdocs coming from other (mid-latitudes) countries always struggle with it. So the idea is to share the knowledge we have so it becomes less opaque and easier to master for newcomers.
> 
> I hope it clarifies a bit. Let me know as I think it is important for me to clarify it so I can clearly express it.
> Thanks.

This actually is a great clarification! Thanks for taking your time to make this clear

**Comment by dblana** [comment]
> I included a README file with LICENSE and these two files are available at:
> 
> * https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/README.md
> * https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/LICENSE.md

Your README file is so good! I will shamelessly steal bits of it :heart_eyes:

**Comment by annefou** [comment]
Thanks! I copy/paste a lot too... and grabbing lots of good ideas too!

**Comment by annefou** [comment]
I have created and updated my repository with [CONTRIBUTING](https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/CONTRIBUTING.md) guidelines and [CODE OF CONDUCT](https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/CODE_OF_CONDUCT.md):

https://github.com/NordicESMhub/nordicesmhub.github.io

And the rendered website is at https://nordicesmhub.github.io/

I have started to create a few issues but need to clarify as many are probably not very clear. 

Feedback is welcome.

**Comment by dblana** [comment]
> I have created and updated my repository with [CONTRIBUTING](https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/CONTRIBUTING.md) guidelines and [CODE OF CONDUCT](https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/CODE_OF_CONDUCT.md):
> 
> https://github.com/NordicESMhub/nordicesmhub.github.io
> 
> And the rendered website is at https://nordicesmhub.github.io/
> 
> I have started to create a few issues but need to clarify as many are probably not very clear.
> 
> Feedback is welcome.

I'm suffering from repository envy, your project looks great! :heart:  :+1: 

I am trying to write my contributing guidelines, and I can't decide at what level to set the github guide. [Yours](https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/CONTRIBUTING.md#using-github) assumes (I think) a certain level of confidence with github, so might be difficult for complete beginners to follow. The one from the [STEMM role models project](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/CONTRIBUTING.md) is geared towards complete beginners... :confused: Thoughts?

**Comment by annefou** [comment]
@dblana You are right. I need to rework my contributing guidelines and my website to make it easier to contribute. I would like students to contribute so it needs to be easier. 
Thanks for your feedback.

**Comment by annefou** [comment]
First step: I added a "Improve this page" button in https://nordicesmhub.github.io/ to make it easier to update the website.

I know I still need to work on my contributing guidelines and add "first issues"... It is not so easy!
