### ISSUE TITLE
Young Accessibility Leaders

### ISSUE THREAD

**Issue by theo-bech** [MozillaFestival/open-leaders-7#51]
Project Lead: theo-bech

Mentor: johnantoni

Welcome to OL7, Cohort C! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 30): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 6): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 13): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 20): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [x] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [ ] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by theo-bech** [comment]
## Vision Statement:

I hope to work with secondary education professionals, developers, and people with disabilities or in the disability field to create a hands-on curriculum on disability and  assistive technology so that middle and high school students can acquire technological skills in a context that inspires their use for positive impact.

I'm working open because I seek to build a community of contributors able to expand on the curriculum and adjust it to their communities' resources and reality of disability, and because a lot of great assistive tech is being made by people who keep their projects open.

**Comment by dblana** [comment]
I love your project, and your vision statement is great! :+1:

**Comment by ghost** [comment]
I'd love to hear more! I have a long term plan to secure funding to draft curricular guidelines or a textbook of some sort for developers on legal matters, including accessibility.

**Comment by theo-bech** [comment]
[Open Canvas](url
![image](https://user-images.githubusercontent.com/46923787/52659513-13341380-2f06-11e9-9eba-77b65cdb3a47.png)
)

**Comment by theo-bech** [comment]
[Open Canvas](https://docs.google.com/presentation/d/1c8NkXFkko-qsd7bGAEvzUhPUfZqRpDSSrHxK0OvjfOA/edit?usp=sharing)

**Comment by theo-bech** [comment]
> 
> 
> I'd love to hear more! I have a long term plan to secure funding to draft curricular guidelines or a textbook of some sort for developers on legal matters, including accessibility.

@webdevlaw thank you! Part of this project is documenting tutorials on accessibility, although the intended audience is teachers who want to introduce their class to assistive tech.

**Comment by theo-bech** [comment]
# Roadmap

**_Let's create an open curriculum on assistive technology for middle and high school students!_**

Project-driven tech classes in secondary education (IT, robotics, etc.) could have a much greater influence on students if they covered the ways in which technology can be used for positive community engagement. A curriculum on assistive technology - any tools used by people with disabilities - could familiarize students with disability and accessibility, offer an example of the work engineers and developers do to assist people with disabilities, and inspire them to effect change in their communities as future professionals. 

Young Accessibility Leaders aims to do just that: create a hands-on curriculum on assistive technology as well as a platform where educators can access the materials and collaborate with developers, disability professionals, and people with disabilities to evaluate and contribute to the resources available. 

The following roadmap lists the Milestones and corresponding tasks **as of 3/2/2019**:

## Milestone: Complete Introductory Course

> The introductory course gives students a taste of what's ahead, familiarizing them with  the concepts of disability,  accessibility, and assistive technology, as well some of the challenges in the field.

- [ ] Compile teacher's guide.
- [ ] Translate introductory course into English.

## Milestone: Complete Project 1 Study & Teaching Materials

> Project 1 is a smart doorbell for people with [hearing](https://www.disabled-world.com/disability/types/hearing/) and/or [mobility](https://www.disabled-world.com/disability/types/mobility/) impairments, built using a RaspberryPi and Python code. It's already been taught in a robotics class at the Model Experiment Junior High School of the University of Macedonia, so most of the resources are complete!

- [ ] Complete presentation.
- [ ] Compile teacher's guide. 
- [ ] Check code.
- [ ] Translate materials to English.

## Milestone: Complete Project 2 Study & Teaching Materials

> Project 2 is a basic mouse stabilizer script concept for people with [Essential Tremor](https://en.wikipedia.org/wiki/Essential_tremor) using AutoHotKey.

- [ ] Complete presentation.
- [ ] Compile teacher's guide. 
- [ ] Check code.

## Milestone: Create GitHub Repository

> The goal of Young Accessibility Leaders is to build a platform where educators and other contributors (especially people with disabilities) will be able to access the project materials and share ideas and resources. Creating a GitHub repository is a good place to start for contributors with technical backgrounds. 

- [x] Create a GitHub repository.
- [ ] Add readme.
- [x] Add license.
- [x] Add contributor guidelines.
- [x] Add code of conduct.
- [ ] Add FAQ

## Milestone: Build Website

> For contributors with non-technical backgrounds and to avoid the hassle of GitHub, we need to build a website where the resources will be more easily accessible.

- [ ] Design website.
- [ ] Add readme, contributor guidelines, code of conduct, and FAQ.
- [ ] Double-check for accessibility!

## Milestone: 4th EKEDISY Conference 

> The curriculum will be presented in the [4th EKEDISY Conference](http://ekedisyconference.weebly.com/) between May 10-12th in Athens. The presentation will be part of a workshop on planning project-driven lessons in assistive technology.

- [ ] Create teacher's guide on designing projects.
- [ ] Create teacher's guide on contacting disability organizations/hosting speakers with disabilities. 
- [ ] Prepare workshop/conference materials.

## Milestone: Compile GitBook Guide

> It'll be nice to have all teaching materials in pdf or e-book format. 

- [ ] Create a book.
- [ ] Curate and adjust materials.
- [ ] Check for accessibility (alt-text, visuals).

## Milestone: Expand Curriculum/Enhance Availability

> The curriculum needs more projects, and all existing resources need to be translated into other languages to increase reach/impact.

- [ ] Translate existing materials into French. 
- [ ] Translate existing materials into Spanish.
- [ ] Translate existing materials into German.
- [ ] Create Project 3.

**Comment by nor-mn** [comment]
A well-worked roadmap, the vision of the project is well focused. :100: 

[la LIBREría #47 ](https://github.com/MozillaFestival/open-leaders-7/issues/47)

**Comment by dblana** [comment]
Nice Open Canvas and very detailed roadmap! 

As a biomedical engineer, I work with people who have movement problems. It will be great if your curriculum inspires future engineers! I look forward to seeing how I can contribute :smiley:

**Comment by theo-bech** [comment]
> 
> 
> Nice Open Canvas and very detailed roadmap!
> 
> As a biomedical engineer, I work with people who have movement problems. It will be great if your curriculum inspires future engineers! I look forward to seeing how I can contribute 😃

@dblana Thanks! I've only worked on assistive tech with a couple of biomedical engineers so I'm still figuring out the contribution details for you guys, but I really appreciate your enthusiasm 😃

**Comment by theo-bech** [comment]
Made a [repository](https://github.com/theo-bech/Young-Accessibility-Leaders) for the project and started drafting the [README.md](https://github.com/theo-bech/Young-Accessibility-Leaders/blob/master/README.md) file.

**Comment by scottkildall** [comment]
Very clearly stated and organized. Good work!

**Comment by theo-bech** [comment]
Added [CONTRIBUTING](https://github.com/theo-bech/Young-Accessibility-Leaders/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/theo-bech/Young-Accessibility-Leaders/blob/master/CODE_OF_CONDUCT.md). _Really_ surprised github markdown doesn't support footnotes.

**Comment by dblana** [comment]
Hi Theodore, have you heard of [Makey Makey](https://makeymakey.com/)? 
I saw this webinar and thought you might be interested: [Electrify Assistive Technology](https://zoom.us/webinar/register/1715508730782/WN_dllCXu0RTi6YQxNUFI3W9A) :smiley:

**Comment by theo-bech** [comment]
@dblana it looks like a great source of inspiration, I'll check it out! Thanks 😄

**Comment by theo-bech** [comment]
The [source code](https://github.com/theo-bech/Young-Accessibility-Leaders/blob/master/mouse_stabilizer_English.ahk) for Project 1 of Young Accessibility Leaders ("Basic Mouse Stabilizer for People with Essential Tremor") has been uploaded! It's a basic script for returning the cursor to its original position after a sudden movement has been detected. The main learning objective is to familiarize students with loops, conditional expressions, and the vast potential of the AutoHotKey language for assistive solutions and personal applications.
