### ISSUE TITLE
Movement Analysis Code for Everyone

### ISSUE THREAD

**Issue by dblana** [MozillaFestival/open-leaders-7#54]
Project Lead:
dblana

Mentor:
ottagit

Welcome to OL7, Cohort C! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 30): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 6): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 13): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 20): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [x] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [ ] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by dblana** [comment]
Draft mission statement: I am working with clinicians and researchers in motion analysis labs to share coding resources, so that they can improve and accelerate their analyses.

**Comment by dblana** [comment]
[Open Canvas](https://docs.google.com/presentation/d/13-aTHyCrOqhQL9CFTFJXXBylxYoXxlCMjbxi6mb8WEI/edit?usp=sharing)

**Comment by dblana** [comment]
**Roadmap**

The use of computer code can greatly benefit clinical movement analysis. It can save time and reduce errors by automating routine tasks, and it can produce new insights by enabling complex calculations. However, not everyone has the skills or time to learn how to develop their own code.
 
We are proposing to develop a free online platform for sharing code, which will also include step-by-step tutorials on how to develop and use it. People with technical skills will be able to collaborate, create new tools, and easily share them among all motion analysis labs. Beginners who are keen to develop coding skills will find a library of tutorials and example code to support their learning. Researchers and clinicians working on motion analysis who would like to use code but do not have time or interest in developing it themselves, will be able to easily find relevant resources, with instructions and examples of use.
 
**Milestone: Clinical Movement Analysis Society (CMAS) annual meeting**
It would be great to have a website by the CMAS annual meeting, April 25-26 2019!

- Create github repository
- Add readme
- Add code of conduct
- Add contributor guidelines
- Add FAQ

**Milestone: Example code**
The example code we will provide initially will be in Python and focus on how to work with C3D files (the de facto standard for movement analysis data). 

- Add Python code to extract different types of information from C3D files and visualise it
- Add tutorial to explain the code
- Add a ready-to-use application: Python code to calculate the gait profile score and movement analysis profile
 
**Milestone: Workshop for CMAS labs**
We will have a one-day coding workshop for UK CMAS labs (sometime in the summer 2019). We already have funding for one travel grant per CMAS-accredited lab, to encourage participation from as many members of the CMAS community as possible.

- Arrange speakers
- Create workshop material

**Comment by annefou** [comment]
Nice roadmap. I still need to finalize mine... I think I'll steal your idea to have a workshop as a milestone! That's a very motivating target!

**Comment by ottagit** [comment]
@dblana Good job on both your open canvas and project roadmap; I like the clarity and precision of the former, and just enough detail provided in the roadmap at this stage of the project. Thanks @annefou for your feedback. Hope to see more interactions on this issue :+1: :+1:

**Comment by mrpandey** [comment]
That's a good mission statement - clear and concise. And that's an even better roadmap! I am looking forward to contribute if my skill-set matches the requirements.

**Comment by ottagit** [comment]
@mrpandey many thanks for your feedback. Would be glad to have you on board @dblana

**Comment by theo-bech** [comment]
Very concise vision statement, and a great project overall! Agree with @annefou, the workshop as a milestone is an excellent idea.

**Comment by balicea** [comment]
Mission statement is very to the point. A few clarifications:

1) under "key metrics": what's more important in terms of code shared, quality or quantity? Are there annotation or formatting standards that the community must meet?

2) under "solution": will your tutorials be stylized as a Wiki, a set of YouTube videos, or as a more standard technical doc? What is most accessible to your community?

**Comment by dblana** [comment]
> Mission statement is very to the point. A few clarifications:
> 
> 1. under "key metrics": what's more important in terms of code shared, quality or quantity? Are there annotation or formatting standards that the community must meet?
> 2. under "solution": will your tutorials be stylized as a Wiki, a set of YouTube videos, or as a more standard technical doc? What is most accessible to your community?

These are excellent points! :smiley: 

1. On quality vs quantity: I am keen to get as many people involved as possible, and most of them do not have any formal computer science training... so I guess quantity is more important. But we should include guidelines for writing good software that can be shared, thank you for pointing that out!

2. My thought was that the tutorials would be simple documents, because I don't know how to make YouTube videos myself - but other contributors might! I will add that to the list of ways people can contribute :+1:

**Comment by dblana** [comment]
Busy week, but I managed to make a [repository](https://github.com/cmasuki/open-code) for the project, and started the [README.md file](https://github.com/cmasuki/open-code/blob/master/README.md). A lot of construction signs :construction: everywhere...

**Comment by annefou** [comment]
Nice! I also created my [README.md](https://github.com/NordicESMhub/nordicesmhub.github.io/blob/master/README.md) but should definitely use this construction sign :construction: (Thanks I did not know it!!!) to show it is not finalized.

**Comment by dblana** [comment]
So many emojis... https://gist.github.com/rxaviers/7360908

**Comment by annefou** [comment]
:clap: So cool!!! Thanks for sharing!

**Comment by theo-bech** [comment]
A very clear open canvas, it helped me figure out how to make mine more comprehensive!

**Comment by scottkildall** [comment]
Wow, good work here. At first I got a little tripped up in the specifics, e.g. does "clinical movement analysis" mean? Then, when reading more deeply, it's all there. So, perhaps an example in the ReadMe for a more general audience, if you want to serve that community (which is where you're getting feedback) would be helpful. Thanks!

**Comment by dblana** [comment]
> Wow, good work here. At first I got a little tripped up in the specifics, e.g. does "clinical movement analysis" mean? Then, when reading more deeply, it's all there. So, perhaps an example in the ReadMe for a more general audience, if you want to serve that community (which is where you're getting feedback) would be helpful. Thanks!

Thank you! That's a great idea :+1:

**Comment by dblana** [comment]
@scottkildall As I am learning how github works, I added your suggestion as the first issue: https://github.com/cmasuki/open-code/issues

**Comment by dblana** [comment]
I updated the [contributing guidelines](https://github.com/cmasuki/open-code/blob/master/CONTRIBUTING.md) and I'd love some feedback! I've tried to make it easy enough for beginners, but not too long... Is there sufficient information there to get people started? How much info should I provide about Git? :grimacing: Any comments/suggestions would be greatly appreciated! :pray:
