### ISSUE TITLE
D3 Graph Theory

### ISSUE THREAD

**Issue by mrpandey** [MozillaFestival/open-leaders-7#65]
Project Lead: [mrpandey](https://github.com/mrpandey)
Project's GitHub Link: [D3 Graph Theory](https://github.com/mrpandey/d3graphTheory)
Mentor: [shadab-entrepreneur](https://github.com/shadab-entrepreneur)

Welcome to OL7, Cohort C! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 30): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 6): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 13): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 20): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [x] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [x] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by mrpandey** [comment]
**Vision Statement:** I wish to work with open source enthusiasts to further develop [D3 Graph Theory](https://github.com/mrpandey/d3graphTheory) so that people can learn [graph theory](https://en.wikipedia.org/wiki/Graph_theory) in an interactive, visual, free and open environment.

**Comment by annefou** [comment]
Super cool tool; and very useful. That a very clear vision statement and I am sure you will have lots of contributors! Well done.

**Comment by StarWonder67** [comment]
Your vision statement is extremely clear and to the point.I also checked out the repo you have linked and it looks great.All the best for your project.

**Comment by mrpandey** [comment]
[Link to Open Canvas](https://docs.google.com/presentation/d/18-qkEucCbl_qxsUBwGGPpMfO-Ln8lurvLk4io7iXDTE/edit?usp=sharing)

**Comment by mrpandey** [comment]
View the updated roadmap [here](https://github.com/mrpandey/d3graphTheory/blob/master/ROADMAP.md).

## Draft Roadmap

D3 Graph Theory is a front-end project aimed at anyone who wants to learn [graph theory](https://en.m.wikipedia.org/wiki/Graph_theory). It provides a quick and interactive introduction to the subject. The visuals used in the project makes it an effective learning tool.

Under project track (Cohort C) of Mozilla Open Leaders 7, the aim is to expand the project beyond introductory level, make it more user friendly and reach more users and contributors.

### Milestone 0: Be contributor friendly
- [x] Create markdown for [code of conduct](https://github.com/mrpandey/d3graphTheory/blob/master/CODE_OF_CONDUCT.md).
- [x] Create markdown for [contributing guidelines](https://github.com/mrpandey/d3graphTheory/blob/master/CONTRIBUTING.md).
- [x] Create markdown for explaining how project works so that contributors don't have to guess.

### Milestone 1: Convert code to d3 v5
Most of the code driving the visualizations is written in v3 of d3.js. However, newer and more optimized v5 of d3.js is available. So we need to rewrite the code in d3 v5.

### Milestone 2: UI
- Improve the user interface of main app.
- A dark theme.

### Milestone 3: Faster math rendering
KaTeX is much faster than LaTeX for rendering mathematics symbols on a webpage. D3 Graph Theory currently uses LaTeX. We need to convert the LaTeX code to KaTeX and complete the replacement.

### Milestone 4: Add more topics
Expand the chapters (aka units) to cover more topics. List of todo topics will be updated.

**Comment by scottkildall** [comment]
Wow, I like how well-organized you are! As someone who does some coding and D3 work and teaches data visualization, I still had to look up what Graph Theory is. I'd suggest linking to Wikipedia/your favorite definition would be helpful.

**Comment by mrpandey** [comment]
[This](https://github.com/mrpandey/d3graphTheory/blob/master/README.md) is the link to README.md for D3 Graph Theory.
