### ISSUE TITLE
ChromesomeJS

### ISSUE THREAD

**Issue by peoplenarthax** [MozillaFestival/open-leaders-7#79]
Project Lead: Angel Paredes Barato

Mentor: Alexander Kutschera

Welcome to OL7, Cohort C! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 30): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 6): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 13): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 20): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [x] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [x] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [x] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by peoplenarthax** [comment]
The Vision of ChromesomeJS:
In ChromosomeJS a group of Developers and Computer Scientist work together to develop a tool that could be useful to develop Genetic Algorithms in an easy way so that anyone could use it, helping to democratise Genetic Algorithms and reducing development time.

**Comment by peoplenarthax** [comment]
Open Canvas: https://docs.google.com/presentation/d/1llTPJWlARaYRPad0MRYUlYrXy7Y62ZxGs-VrYFVAyG0/edit?usp=sharing

**Comment by dblana** [comment]
> Open Canvas: https://docs.google.com/presentation/d/1llTPJWlARaYRPad0MRYUlYrXy7Y62ZxGs-VrYFVAyG0/edit?usp=sharing

Hey, interesting project! Since your focus is Genetic Algorithms, I think that your Unique Value Proposition (in your Open Canvas) should mention GA.  

I look forward to seeing your Roadmap! :smiley:

**Comment by kristinellis** [comment]
> Open Canvas: https://docs.google.com/presentation/d/1llTPJWlARaYRPad0MRYUlYrXy7Y62ZxGs-VrYFVAyG0/edit?usp=sharing

This is AWESOME! (I am one of the people you mentioned who is curious about genetic algorithms 😄)
Interested to know what kind of documentation/writing is needed for contribution, and if those contributors would need specific technical expertise to be able to help. Excited to see how this develops!

**Comment by peoplenarthax** [comment]
> > Open Canvas: [docs.google.com/presentation/d/1llTPJWlARaYRPad0MRYUlYrXy7Y62ZxGs-VrYFVAyG0/edit?usp=sharing](https://docs.google.com/presentation/d/1llTPJWlARaYRPad0MRYUlYrXy7Y62ZxGs-VrYFVAyG0/edit?usp=sharing)
> 
> This is AWESOME! (I am one of the people you mentioned who is curious about genetic algorithms 😄)
> Interested to know what kind of documentation/writing is needed for contribution, and if those contributors would need specific technical expertise to be able to help. Excited to see how this develops!

Hello, for the writing part I think that is important to understand basics of Genetic Algorithms to try to drive users through tutorials or have a correct use of different terms (chromosome, individual, offspring... ). But I think that once someone more technical can provide some guidelines anybody should be able to rephrase it :D

> > Open Canvas: [docs.google.com/presentation/d/1llTPJWlARaYRPad0MRYUlYrXy7Y62ZxGs-VrYFVAyG0/edit?usp=sharing](https://docs.google.com/presentation/d/1llTPJWlARaYRPad0MRYUlYrXy7Y62ZxGs-VrYFVAyG0/edit?usp=sharing)
> 
> Hey, interesting project! Since your focus is Genetic Algorithms, I think that your Unique Value Proposition (in your Open Canvas) should mention GA.
> 
> I look forward to seeing your Roadmap! 😃

Thanks for the feedback, the canvas reflect this now 😉

**Comment by peoplenarthax** [comment]
The roadmap is available as a [Github Project](https://github.com/peoplenarthax/chromosome-js/projects/1) and is aiming for the MVP of the project.

This means that by the end of Project a MVP of ChromesomeJS should be available to be used by others.

**Milestone: Framework**

Right now, Chromesome was only oriented to offer utility functions, but this still limits developers to have their own implementation of the Genetic Algorithm (Define the loop, conditions...), hence the problem of people understanding how to implement their own ones is still there. This milestone is to create a framework that can do inversion of control and just accept inputs from the user and save developers the time of developing the rest.

**Milestone: Expanding utility functions**

Utility functions are functions that can be use freely, without the need of any framework or additional library. Usually they have one single purpose, e.g. One Point Crossover, this will take as input 2 arrays or objects and it will perform a simple one point crossover to it (swap values given a point or feature). This allow you to create your own genetic algorithm without having to implement all the functions that you may need (selection functions, crossover functions, fitness functions, mutation functions...)

To make this suitable for more people, ChromesomeJS needs to offer a wider variaty of utility functions regarding offspring, selection, mutation and also have a clear API so that the framework can still deal with this changes.

**Milestone: Documentation**

A Developer portal that guide you through the usage of the library and also offer different examples and details explanations about Genetic Algorithms. It also should be more clear the guidelines for those that want to contribute to the documentation of the project (localisation, extension, corrections...)

**Comment by scottkildall** [comment]
I love the name, by the way. What is a "utility function" anyhow? I do some coding, but not sure what this means. Maybe I'm missing something, but in the interest of the xkcd simplifying, I'd love to see this defined. Very cool framework possibilities!

**Comment by peoplenarthax** [comment]
> I love the name, by the way. What is a "utility function" anyhow? I do some coding, but not sure what this means. Maybe I'm missing something, but in the interest of the xkcd simplifying, I'd love to see this defined. Very cool framework possibilities!

Nice comment, it is something that is so clear in my mind that I totally dismissed explaining it further. I updated the roadmap with the definition and an example. But basically a utility function is a pure function, with a single purpose and that does not need a framework or another library to work. For example, a typical utility function could be Math.power, Math.sqrt, Math.abs... But in the case of ChromosomeJS it is a crossover function, a selection function etcetera, so people can use them without having to use the rest of ChromosomeJS when developing Genetic Algorithms

**Comment by akram-mohammed** [comment]
Interesting!
