### ISSUE TITLE
Opentrons Protocol Library

### ISSUE THREAD

**Issue by kristinellis** [MozillaFestival/open-leaders-7#99]
**Project Lead:**
- [Kristin Ellis](https://github.com/kristinellis) 👽 

**Teammates:**
- [Laura Cox](https://github.com/Laura-Danielle)
- [Alise Au](https://github.com/ahiuchingau)

**Mentor:**
- [Jason Heppler](https://github.com/hepplerj)

Welcome to OL7, Cohort C! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 30): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 6): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 13): Mentorship call
- [x] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [x] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 20): Cohort Call (Build for Understanding)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.
- [x] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [x] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [x] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [x] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [x] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [x] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by kristinellis** [comment]
Wow, we've gotta do a better job of keeping up with our Github updates!!

**Week of 2/4/19**

**Vision Statement:** _We're collaborating with the [Opentrons](https://opentrons.com/) community to [design a common platform](https://protocols.opentrons.com/) that encourages discovery, creation, contribution, and sharing of automated scientific workflows built on the Opentrons system._

**Mission Statement:** _We’re working open in order to empower the scientific community to leverage each others’ unique expertise, which will improve reproducibility, make complicated workflows more accessible, and open more avenues for scientific collaboration._

**Comment by kristinellis** [comment]
**Week of 2/10/19**

**[Open Canvas First Draft](https://docs.google.com/presentation/d/13CV7karDYFTbfffBRu15nKVIIDm46BF7TPQdnTD_k9Q/edit?usp=sharing)**

**[Roadmap First Draft](https://github.com/Opentrons/Protocols/issues/644)**

**Comment by samcillabaakojr** [comment]
Great vision! Though your major focus is on the scientific community, do you have room for the non-scientific communities hoping to improve reproducibility using robots? I hope to learn more :)

**Comment by nor-mn** [comment]
I really like your project vision @kristinellis 
Although for a non-scientific community it may have to relate to study techniques and establish a way of how to present a project with some fixed points.
Successes!
[la LIBREría #47 ](https://github.com/MozillaFestival/open-leaders-7/issues/47)

**Comment by kristinellis** [comment]
> Great vision! Though your major focus is on the scientific community, do you have room for the non-scientific communities hoping to improve reproducibility using robots? I hope to learn more :)

@samcilla We do have room for this! Although our platform is geared primarily towards biologists (of the sort that have to move around tiny amounts of liquid to assemble complex reactions), we hope to share their expertise with non-experts who want to do biology as well -- like designers creating new biomaterials, artists exploring the intersection of bio+experience, and more!

Our starting point is figuring out how to enable these types of sharing activities from our core group of scientific community members, but we hope to make this available to anyone :)

**Comment by kristinellis** [comment]
OK FOLKS! We have an OPEN LICENSE and a README! 🎉 

The Opentrons platform is currently licensed under the [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/). You can check this out in our Github [here](https://github.com/Opentrons/opentrons/blob/edge/LICENSE).

Note that our README needs updating and is a ✨ **work in progress** ✨ - we would love to hear from all of you about improvements we can make!

**[Protocol Library README](https://github.com/Opentrons/Protocols#opentrons-protocol-library)**

**Comment by kristinellis** [comment]
> I really like your project vision @kristinellis
> Although for a non-scientific community it may have to relate to study techniques and establish a way of how to present a project with some fixed points.
> Successes!
> [la LIBREría #47 ](https://github.com/MozillaFestival/open-leaders-7/issues/47)

THANK YOU! Appreciate the vote of confidence and the feedback. All done with help and collabs from @ahiuchingau and @laura-danielle!

**Comment by scottkildall** [comment]
Great Mission Statement and Vision Statement! Echoing the non-scientific communities — as an artist who works with biology and scientists at times, I'd love to feel invited here. e.g. "empower the scientific community" - which I'm not part of vs. "scientific collaboration" which I am part of. Thanks!

**Comment by kristinellis** [comment]
> Great Mission Statement and Vision Statement! Echoing the non-scientific communities — as an artist who works with biology and scientists at times, I'd love to feel invited here. e.g. "empower the scientific community" - which I'm not part of vs. "scientific collaboration" which I am part of. Thanks!

I love this bit of feedback - thank you!! We'll definitely take this into consideration and work on making our language more inclusive!

**Comment by kristinellis** [comment]
Hello!

Here's the first draft of our [**Vision Presentation!**](https://docs.google.com/presentation/d/12evj9uNiJsVFjYcRweOvCck2hYgjpLQ49oQyWYutsfQ/edit?usp=sharing).  🎉 🤖 
We would love to hear feedback on this from our cohort pals - please let us know what you think!

**Comment by hepplerj** [comment]
I think your presentation is great! A couple things stand out to me: 

- You mention in your vision slide that you're "collaborating with the scientific community," but two slides later say that everyone is biotech and can participate. I think there might be a slight disconnect here: for example, I'm an environmental historian by training (biology, yeah! 🌱) who writes about urban sustainability, but I'm not sure I'd consider myself part of the "scientific community." So, I wonder if there's a way to either change the vision so it doesn't mention this community, or define this community in some way? Happy to chat more to clarify my own thinking around this. 
- I love your penultimate slide pointing to what's next. And I think as we continue to develop contributor guidelines and outline ways people can get involved more clearly (in the README, GitHub issues, etc.) that slide could become even more specific (e..g, at some point, instead of mentioning you're developing guidelines, you can point directly to significant ways to contribute).

**Comment by kristinellis** [comment]
Hello everyone!

We've made it through 15 weeks! 🎉 🤖 👩‍🔬 🙌 💻 👩‍💻 ☕️ 🙃 

Here's the FINAL DRAFT of our [Vision Presentation](https://docs.google.com/presentation/u/0/?tgif=d), in which we invite ALL THE PEOPLE OF THE INTERNET to come contribute to our platform as part of our first-ever [Hack-A-Tron](https://www.mozillapulse.org/entry/1141)! 🌍

Please continue to follow along with our journey on our [Github](http://github.com/opentrons) and if you have any questions, please email us at community@opentrons.com - we'd love to hear from you!
